### ISSUE TITLE
[Feature] 使用阿里云OSS存放项目的静态资源

### ISSUE THREAD

**Issue by chi3316** [chi3316/campus-errand-backend#3]
**任务描述：**
将前端项目中的静态图片和用户头像存放到阿里云OSS（对象存储服务）中，以提高资源的存储和访问效率，并确保静态资源的安全性和可靠性。

**任务细节：**
1. 将前端项目中的所有静态图片(static/目录中)上传至阿里云OSS，包括但不限于项目中使用的图标、背景图片等。
2. 将用户上传的头像图片存放在阿里云OSS中，用于用户头像的显示和管理。

**具体步骤：**
1. **上传静态图片至OSS：**
   - 遍历前端项目中的所有静态图片文件，并使用阿里云OSS提供的SDK或API进行批量上传至指定的OSS存储空间。
   - 确保上传的图片文件在OSS中的存放路径和前端项目中的相对路径保持一致，以便项目能够正确访问和加载图片资源。

2. **处理用户头像上传：**
   - 在用户头像上传功能中，将用户上传的头像图片直接上传至阿里云OSS，并将返回的图片URL保存到用户信息中。
   - 确保用户头像图片在OSS中的存放路径和用户信息中保存的路径一致，以便在用户头像展示时能够正确加载。

**预期效果：**
- 通过将静态资源存放到阿里云OSS中，可以有效减轻前端服务器的负载，提高网站的加载速度和访问效率。
- 通过OSS提供的高可用性和持久性存储，确保静态资源的安全性和可靠性，减少因服务器故障或网络问题导致的静态资源丢失风险。

**Comment by chi3316** [comment]
@1037827920 please take a look😊

**Comment by 1037827920** [comment]
我来！
